### ISSUE TITLE
Captured image is actually a screenshot, not a photo from camera

### ISSUE THREAD

**Issue by darina-techery** [AFathi/ARVideoKit#2]
Hi! Today my colleagues and I experimented with the framework and took a photo using photo() method of recorder object. However, the resulting image had dimensions equal to screen ones, which means it was simply a screenshot, not a photo taken by phone camera, which has much higher resolution. Is that an expected behavior?

**Comment by AFathi** [comment]
Hey @darina-techery!

Great question. 

In order to retrieve a rendered image, `ARVideoKit` renders `ARFrame`'s raw [`capturedImage`](https://developer.apple.com/documentation/arkit/arframe/2867984-capturedimage) with the SceneKit or SpriteKit content. 

The reason the image captured is same as the screen size is because the [`photo`](https://github.com/AFathi/ARVideoKit/wiki/RecordAR#func-photo---uiimage) method in `ARVideoKit` renders the image size based on the resolution of [`capturedImage`](https://developer.apple.com/documentation/arkit/arframe/2867984-capturedimage) from [`ARFrame`](https://developer.apple.com/documentation/arkit/arframe/). 
 
Check [Apple's documentation for more information](https://developer.apple.com/documentation/arkit/arframe/2867984-capturedimage).

Additionally, if you're trying to check the raw buffer quality you can use the [protocol method](https://github.com/AFathi/ARVideoKit/wiki/RenderARDelegate#func-framedidrender-buffercvpixelbuffer-with-timecmtime-using-rawbuffercvpixelbuffer) provided in ARVideoKit to retrieve both raw & rendered buffers. Or simply retrieve the raw buffers from your `ARFrame`.

I hope that helped and made things clearer!

Please comment on this thread if you have a further question. Otherwise, I'll close the issue.

-Ahmed

**Comment by darina-techery** [comment]
Hey @AFathi,

Thank you for a swift response! 

As I am new to iOS development, I mostly rely on my colleagues' comments, and they say that `capturedImage` contains only raw image from camera without additional AR drawings. Does it mean we have to replicate the built-in ARKit logic to apply these drawings to the bigger image, as they do to render screen-based image?

**Comment by AFathi** [comment]
Hey @darina-techery,

You don't have to do that. [ARVideoKit](http://github.com/AFathi/ARVideoKit) already handles all that for you!

Check [ARVideoKit Documentation](https://github.com/AFathi/ARVideoKit/wiki) & [RecordAR](https://github.com/AFathi/ARVideoKit/wiki/RecordAR) for more information.

-Ahmed
